AWSTemplateFormatVersion: 2010-09-09
Description: Hosted zone

Parameters:
  DomainName:
    Type: String

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneTags:
        Key: Updated
        Value: 12Apr2026

Outputs:
  HostedZoneId:
    Value: !Ref HostedZone
    Export:
      Name: hosted-zone-id
  NameServers:
    Value: !Join [", ", !GetAtt HostedZone.NameServers]
