AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambdas and API Gateway

Parameters:
  AppBaseUrl:
    Type: String
  AllowedOrigins:
    Type: String
  LambdaSourceBucketName:
    Type: String
  StageName:
    Type: String

Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64

Resources:

  RondeauApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: rondeau-api
      OpenApiVersion: 3.0.4
      StageName: !Ref StageName
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${LambdaSourceBucketName}/openapi.yaml

  ApiAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ApiAuthorizer
      Role: !ImportValue api-lambda-role-arn
      Handler: index.handler
      CodeUri: ./src/api-authorizer/
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !ImportValue cognito-user-pool-client-id
          COGNITO_USER_POOL_ID: !ImportValue cognito-user-pool-id

  ApiAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiAuthorizer
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RondeauApi}/*

  ApiAuthCallback:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ApiAuthCallback
      Role: !ImportValue api-lambda-role-arn
      Handler: index.handler
      CodeUri: ./src/api-auth-callback/
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !ImportValue cognito-user-pool-client-id
          COGNITO_DOMAIN: !ImportValue cognito-user-pool-domain
          APP_BASE_URL: !Ref AppBaseUrl
          ALLOWED_ORIGINS: !Ref AllowedOrigins

  ApiAuthCallbackPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiAuthCallback
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RondeauApi}/*

  ApiAuthLogout:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ApiAuthLogout
      Role: !ImportValue api-lambda-role-arn
      Handler: index.handler
      CodeUri: ./src/api-auth-logout/
      Environment:
        Variables:
          APP_BASE_URL: !Ref AppBaseUrl

  ApiAuthLogoutPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiAuthLogout
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RondeauApi}/*

  ApiStatus:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ApiStatus
      Role: !ImportValue api-lambda-role-arn
      Handler: index.handler
      CodeUri: ./src/api-status/

  ApiStatusPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ApiStatus
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RondeauApi}/*

Outputs:
  ApiUrl:
    Value: !Sub https://${RondeauApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
    Export:
      Name: api-gateway-url
