AWSTemplateFormatVersion: 2010-09-09
Description: Web Application Firewall to secure CloudFront distribution

Resources:
  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: CLOUDFRONT
      VisabilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: WebAcl
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet

Outputs:
  WebAclId:
    Value: !Ref WebAcl
    Export:
      Name: webacl-id
  WebAclArn:
    Value: !GetAtt WebAcl.Arn
    Export:
      Name: webacl-arn
