name: rondeau

services:
  api:
    build:
      context: ./api/ 
    platform: linux/arm64
    image: ${IMAGE_REGISTRY:-local}/${IMAGE_REPOSITORY_NAME:-local}:api-${GIT_SHA:-nocommit}
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync+restart
          path: ./api/src
          target: /api/src
          initial_sync: true
        - action: rebuild
          path: ./api/package.json
