AWSTemplateFormatVersion: 2010-09-09
Description: Storage for frontend assets.

Parameters:
  FrontendAssetsBucketName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref FrontendAssetsBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${S3Bucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/*

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Export:
      Name: frontend-assets-bucket-name
  BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Export:
      Name: frontend-assets-bucket-arn
  BucketRegionalDomainName:
    Value: !GetAtt S3Bucket.RegionalDomainName
    Export:
      Name: frontend-assets-bucket-domain
