AWSTemplateFormatVersion: 2010-09-09
Description: Lambdas directly in service of the API Gateway.

Parameters:
  AppBaseUrl:
    Type: String
  LambdaSourceBucketName:
    Type: String

Resources:

  ApiAuthCallback:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthCallback
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthCallback
      Role: !ImportValue api-lambda-role-arn
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !ImportValue cognito-user-pool-client-id
          APP_BASE_URL: !Ref AppBaseUrl
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-auth-callback.zip

  ApiAuthLogout:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthLogout
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthLogout
      Role: !ImportValue api-lambda-role-arn
      Environment:
        Variables:
          APP_BASE_URL: !Ref AppBaseUrl
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-auth-logout.zip

  ApiStatus:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiStatus
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiStatus
      Role: !ImportValue api-lambda-role-arn
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-status.zip
