AWSTemplateFormatVersion: 2010-09-09
Description: Lambdas directly in service of the yeschef API Gateway.

Parameters:
  LambdaRole:
    Type: String
  LambdaSourceBucketName:
    Type: String

Resources:
  ApiAuthCallback:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthCallback
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthCallback
      Role: !Ref LambdaRole
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-auth-callback.zip
  ApiAuthLogout:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthLogout
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthLogout
      Role: !Ref LambdaRole
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-auth-logout.zip
  ApiAuthorizer:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthorizer
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthorizer
      Role: !Ref LambdaRole
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-authorizer.zip
  ApiStatus:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiStatus
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiStatus
      Role: !Ref LambdaRole
      Code:
        S3Bucket: !Ref LambdaSourceBucketName
        S3Key: api-status.zip
