AWSTemplateFormatVersion: 2010-09-09
Description: Lambdas directly in service of the yeschef API Gateway.

Parameters:
  authCallbackRedirectLocation:
    Type: String
    Description: ApiAuthCallback redirect location after token exchange.
  authLogoutRedirectLocation:
    Type: String
    Description: ApiAuthLogout redirect location after Cognito logout.
  cognitoClientId:
    Type: String
    Description: Cognito client ID.
  redirectUri:
    Type: String
    Description: ApiAuthCallback redirect for Cognito authorize.

Resources:
  ApiAuthCallback:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthCallback
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      Environment:
        Variables:
          APP_REDIRECT_LOCATION: !Ref authCallbackRedirectLocation
          COGNITO_CLIENT_ID: !Ref cognitoClientId
          REDIRECT_URI: !Ref redirectUri
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthCallback
      Role: arn:aws:iam::312695118281:role/LambdaBasicExecution
      Code:
        S3Bucket: yeschef-lambda-source-0001
        S3Key: api-auth-callback.zip
  ApiAuthLogout:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthLogout
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      Environment:
        Variables:
          APP_REDIRECT_LOCATION: !Ref authLogoutRedirectLocation
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthLogout
      Role: arn:aws:iam::312695118281:role/LambdaBasicExecution
      Code:
        S3Bucket: yeschef-lambda-source-0001
        S3Key: api-auth-logout.zip
  ApiAuthorizer:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiAuthorizer
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiAuthorizer
      Role: arn:aws:iam::312695118281:role/LambdaBasicExecution
      Code:
        S3Bucket: yeschef-lambda-source-0001
        S3Key: api-authorizer.zip
  ApiStatus:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ApiStatus
      Architectures:
        - arm64
      Runtime: nodejs24.x
      Handler: index.handler
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/ApiStatus
      Role: arn:aws:iam::312695118281:role/LambdaBasicExecution
      Code:
        S3Bucket: yeschef-lambda-source-0001
        S3Key: api-status.zip
