AWSTemplateFormatVersion: 2010-09-09
Description: Lambdas directly in service of the yeschef API Gateway.

Parameters:
  lambdaSourceBucketName:
    Type: String
    Default: dev-yeschef-lambda-source-0001

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref lambdaSourceBucketName
