AWSTemplateFormatVersion: 2010-09-09
Description: Lambdas directly in service of the yeschef API Gateway.

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: yeschef-lambda-source-0001
