AWSTemplateFormatVersion: 2010-09-09
Description: EC2 service

Parameters:
  ApiCertificateArn:
    Type: String
  ImageRepositoryName:
    Type: String
  GitSha:
    Type: String
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-arm64
  FckNatAmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-037c5d82ae136c25d

Resources:
  Vpc01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/24
      EnableDnsHostnames: true

  SecurityGroupLoadBalancerApi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupLoadBalancerApi
      GroupDescription: security group load balancer api
      VpcId: !Ref Vpc01

  IngressLoadBalancerApi:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allows traffic from CloudFront
      GroupId: !Ref SecurityGroupLoadBalancerApi
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourcePrefixListId: pl-82a045eb

  LoadBalancerApi:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: LoadBalancerApi
      Scheme: internal
      SecurityGroups:
        - !Ref SecurityGroupLoadBalancerApi
      Subnets:
        - !Ref SubnetPrivate01
        - !Ref SubnetPrivate02

  ListenerApi:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancerApi
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ApiCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupApi

  SecurityGroupApi:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupApi
      GroupDescription: Allow traffic from LoadBalancerApi
      VpcId: !Ref Vpc01

  IngressApi:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allows traffic from LoadBalancerApi
      GroupId: !Ref SecurityGroupApi
      IpProtocol: tcp
      FromPort: 3000
      ToPort: 3000
      SourceSecurityGroupId: !Ref SecurityGroupLoadBalancerApi

  SubnetPrivate01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.64/27
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref Vpc01

  SubnetPrivate02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.96/27
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref Vpc01

  AutoScalingGroupApi:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: AutoScalingGroupApi
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateApi
        Version: !GetAtt LaunchTemplateApi.LatestVersionNumber
      MaxSize: '1'
      MinSize: '1'
      VPCZoneIdentifier: 
        - !Ref SubnetPrivate01
        - !Ref SubnetPrivate02
      TargetGroupARNs:
        - !Ref TargetGroupApi
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300

  TargetGroupApi:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: TargetGroupApi
      VpcId: !Ref Vpc01
      Port: 3000
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /health

  LaunchTemplateApi:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: LaunchTemplateApi
      LaunchTemplateData:
        InstanceType: t4g.nano
        IamInstanceProfile:
          Name: !Ref InstanceProfileApi
        ImageId: !Ref LatestAmiId
        SecurityGroupIds:
          - !Ref SecurityGroupApi
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            dnf update -y
            dnf install docker -y
            systemctl enable --now docker

            aws ecr get-login-password --region ${AWS::Region} | \
              docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
            
            docker pull ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepositoryName}:api-${GitSha}
            docker run -d --restart unless-stopped -p 3000:3000 \
              ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepositoryName}:api-${GitSha}

  InstanceProfileApi:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: InstanceProfileApi
      Roles:
        - !Ref RoleApi

  RoleApi:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RoleApi
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly

  RouteTablePrivate:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc01

  RouteTablePrivateAssociationPrivate01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivate01

  RouteTablePrivateAssociationPrivate02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      SubnetId: !Ref SubnetPrivate02

  RouteFcknat:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTablePrivate
      DestinationCidrBlock: 0.0.0.0/0
      NetworkInterfaceId: !Ref NetworkInterfaceFcknat

  SecurityGroupFcknat:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: SecurityGroupFcknat
      GroupDescription: security group fcknat
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref SecurityGroupLoadBalancerApi
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - SourceSecurityGroupId: !Ref SecurityGroupApi
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      VpcId: !Ref Vpc01

  SubnetPublic01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.0/27
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref Vpc01
      MapPublicIpOnLaunch: true

  NetworkInterfaceFcknat:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: Interface for requests to fck-nat (internet gateway)
      SubnetId: !Ref SubnetPublic01
      GroupSet:
        - !GetAtt [SecurityGroupFcknat, GroupId]
      SourceDestCheck: false

  AutoScalingGroupFcknat:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: AutoScalingGroupFcknat
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateFcknat
        Version: !GetAtt LaunchTemplateFcknat.LatestVersionNumber
      VPCZoneIdentifier:
        - !Ref SubnetPublic01
      Tags:
        - Key: Name
          Value: fck-nat
          PropagateAtLaunch: true
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true

  LaunchTemplateFcknat:
    Type: AWS::EC2::LaunchTemplate
    DependsOn: RoleFcknat
    Properties:
      LaunchTemplateName: LaunchTemplateFcknat
      LaunchTemplateData:
        ImageId: !Ref FckNatAmiId
        InstanceType: t4g.nano
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups:
              - !GetAtt [SecurityGroupFcknat, GroupId]
        IamInstanceProfile:
          Name: !Ref InstanceProfileFcknat
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo "eni_id=${NetworkInterfaceFcknat}" >> /etc/fck-nat.conf
            service fck-nat restart
      
  InstanceProfileFcknat:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: InstanceProfileFcknat
      Roles:
        - !Ref RoleFcknat

  RoleFcknat:
    Type: AWS::IAM::Role
    Properties:
      RoleName: RoleFcknat
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: AttachNatEniPolicy
          PolicyDocument:
            Statement:
              - Action:
                  - ec2:AttachNetworkInterface
                  - ec2:ModifyNetworkInterfaceAttribute
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
        - PolicyName: AssociateNatAddressPolicy
          PolicyDocument:
            Statement:
              - Action:
                  - ec2:AssociateAddress
                  - ec2:DisassociateAddress
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"

  RouteTableMain:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref Vpc01

  RouteTableMainAssociationPublic01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableMain
      SubnetId: !Ref SubnetPublic01

  RouteInternetGateway:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachmentVpc01
    Properties:
      RouteTableId: !Ref RouteTableMain
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CloudFront required internet gateway

  InternetGatewayAttachmentVpc01:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref Vpc01


Outputs:
  LoadBalancerApiArn:
    Value: !Ref LoadBalancerApi
    Export:
      Name: LoadBalancerApiArn
  LoadBalancerApiDomainName:
    Value: !GetAtt LoadBalancerApi.DNSName
    Export:
      Name: LoadBalancerApiDomainName
  ListenerApiArn:
    Value: !Ref ListenerApi
    Export:
      Name: ListenerApiArn
  TargetGroupApiArn:
    Value: !Ref TargetGroupApi
    Export:
      Name: TargetGroupApiArn
  AutoScalingGroupApiName:
    Value: !Ref AutoScalingGroupApi
    Export:
      Name: AutoScalingGroupApiName
