AWSTemplateFormatVersion: 2010-09-09
Description: EC2 service

Parameters:
  ApiCertificateArn:
    Type: String

Resources:
  Vpc01:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/24
      EnableDnsHostnames: true

  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.0/27
      AvailabilityZone: !Select [0, !GetAZs '']
      VpcId: !Ref Vpc01

  PrivateSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.0.32/27
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId: !Ref Vpc01

  InternetGateway01:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: CloudFront Required

  Ig01Vpc01:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway01
      VpcId: !Ref Vpc01

  Sg01:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref Vpc01
      GroupDescription: ALB SG

  Sg01InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allows traffic from CloudFront
      GroupId: !Ref Sg01
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourcePrefixListId: pl-82a045eb

  Alb01:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internal
      SecurityGroups:
        - !Ref Sg01
      Subnets:
        - !Ref PrivateSubnet01
        - !Ref PrivateSubnet02

  AlbListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb01
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref ApiCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: "200"
            ContentType: text/plain
            MessageBody: "Green on track"

Outputs:
  Alb01Arn:
    Value: !Ref Alb01
    Export:
      Name: api-alb-arn
  Alb01DomainName:
    Value: !GetAtt Alb01.DNSName
    Export:
      Name: api-alb-domain-name
