name: deploy-rondeau
on:
  push:
    branches:
      - main
      - dev
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:

  deploy-auth:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup Cognito
        run: |
          aws cloudformation deploy \
          --stack-name auth-cognito \
          --template-file ./cloudformation/auth/cognito/cognito.yaml \
          --parameter-overrides \
            CallbackUrl=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/callback \
            LogoutUrl=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/logout

  deploy-api:
    needs: deploy-auth
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup SAM
        run: pip install aws-sam-cli

      - name: Create IAM roles
        run: |
          aws cloudformation deploy \
          --stack-name api-iam \
          --capabilities CAPABILITY_NAMED_IAM \
          --template-file ./cloudformation/api/iam/iam.yaml

      - name: Setup S3 bucket
        run: |
          aws cloudformation deploy \
          --stack-name api-s3 \
          --template-file ./cloudformation/api/s3/s3.yaml \
          --parameter-overrides \
            LambdaSourceBucketName=${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}

      - name: Create APIGateway and Lambda functions
        run: |
          aws s3 cp ./cloudformation/api/serverless/openapi.yaml s3://${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}

          sam build --template ./cloudformation/api/serverless/serverless.yaml

          sam deploy \
            --stack-name api-serverless \
            --s3-bucket ${{ vars.LAMBDA_SOURCE_BUCKET_NAME }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            "AppBaseUrl=https://${{ vars.DOMAIN_NAME }} \
              AllowedOrigins=${{ vars.ALLOWED_ORIGINS }} \
              LambdaSourceBucketName=${{ vars.LAMBDA_SOURCE_BUCKET_NAME }} \
              StageName=${{ vars.API_STAGE_NAME }}"

  deploy-frontend:
    needs: deploy-api
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup S3 bucket
        run: |
          aws cloudformation deploy \
          --stack-name frontend-s3 \
          --template-file ./cloudformation/frontend/s3/s3.yaml \
          --parameter-overrides \
            FrontendAssetsBucketName=${{ vars.FRONTEND_ASSETS_BUCKET_NAME }}

      - name: Sync frontend assets to S3
        env:
          VITE_COGNITO_CLIENT_ID: ${{ vars.VITE_COGNITO_CLIENT_ID }}
          VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
          VITE_COGNITO_LOGOUT_URI: ${{ vars.VITE_COGNITO_LOGOUT_URI }}
          VITE_COGNITO_REDIRECT_URI: ${{ vars.VITE_COGNITO_REDIRECT_URI }}
        run: |
          npm ci

          npm run build

          aws s3 sync ./dist s3://${{ vars.FRONTEND_ASSETS_BUCKET_NAME }} --delete

      - name: Setup Hosted Zone
        run: |
          aws cloudformation deploy \
          --stack-name frontend-route53 \
          --template-file ./cloudformation/frontend/route53/route53.yaml \
          --parameter-overrides \
            DomainName=${{ vars.DOMAIN_NAME }}

      - name: Setup Cloudfront
        run: |
          aws cloudformation deploy \
          --stack-name frontend-cloudfront \
          --template-file ./cloudformation/frontend/cloudfront/cloudfront.yaml \
          --parameter-overrides \
            DomainName=${{ vars.DOMAIN_NAME }} \
            AcmCertificateArn=${{ vars.DOMAIN_CERTIFICATE_ARN }} \
            StageName=${{ vars.API_STAGE_NAME }}
