name: deploy-rondeau
on:
  push:
    branches:
      - main
      - dev
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:

  deploy-auth:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup Cognito
        run: |
          aws cloudformation deploy \
          --stack-name auth-cognito \
          --template-file ./cloudformation/auth/cognito/cognito.yaml \
          --parameter-overrides \
            CallbackUrl=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/callback \
            LogoutUrl=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/logout

  deploy-api:
    needs: deploy-auth
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup ECR repository
        run: |
          aws cloudformation deploy \
          --stack-name api-ecr \
          --template-file ./cloudformation/api/ecr/ecr.yaml

      - name: Setup VPC and subnets
        run: |
          aws cloudformation deploy \
          --stack-name api-ec2 \
          --template-file ./cloudformation/api/ec2/ec2.yaml \
          --parameter-overrides \
            ApiCertificateArn=${{ vars.API_CERTIFICATE_ARN }}

  deploy-frontend:
    needs: deploy-api
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Setup S3 bucket
        run: |
          aws cloudformation deploy \
          --stack-name frontend-s3 \
          --template-file ./cloudformation/frontend/s3/s3.yaml \
          --parameter-overrides \
            FrontendAssetsBucketName=${{ vars.FRONTEND_ASSETS_BUCKET_NAME }}

      - name: Sync frontend assets to S3
        working-directory: ./webapp
        run: |
          export VITE_COGNITO_CLIENT_ID=$(aws cloudformation describe-stacks \
            --stack-name auth-cognito \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
            --output text)

          export VITE_COGNITO_DOMAIN=$(aws cloudformation describe-stacks \
            --stack-name auth-cognito \
            --query "Stacks[0].Outputs[?OutputKey=='UserPoolDomain'].OutputValue" \
            --output text)

          export VITE_COGNITO_REDIRECT_URI=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/callback
          export VITE_COGNITO_LOGOUT_URI=https://${{ vars.DOMAIN_NAME }}/${{ vars.API_STAGE_NAME }}/auth/logout

          npm ci

          npm run build

          aws s3 sync ./dist s3://${{ vars.FRONTEND_ASSETS_BUCKET_NAME }} --delete

      - name: Setup Hosted Zone
        run: |
          aws cloudformation deploy \
          --stack-name frontend-route53 \
          --template-file ./cloudformation/frontend/route53/route53.yaml \
          --parameter-overrides \
            DomainName=${{ vars.DOMAIN_NAME }}

      - name: Setup WAF for Cloudfront
        id: waf
        run: |
          aws cloudformation deploy \
            --region us-east-1 \
            --stack-name frontend-waf \
            --template-file ./cloudformation/frontend/waf/waf.yaml

          WAF_ARN=$(aws cloudformation describe-stacks \
            --region us-east-1 \
            --stack-name frontend-waf \
            --query "Stacks[0].Outputs[?OutputKey=='WebAclArn'].OutputValue" \
            --output text)

          echo "waf_arn=$WAF_ARN" >> $GITHUB_OUTPUT

      - name: Setup Cloudfront
        run: |
          aws cloudformation deploy \
          --stack-name frontend-cloudfront \
          --template-file ./cloudformation/frontend/cloudfront/cloudfront.yaml \
          --parameter-overrides \
            WebAclArn=${{ steps.waf.outputs.waf_arn }} \
            DomainName=${{ vars.DOMAIN_NAME }} \
            DomainCertificateArn=${{ vars.DOMAIN_CERTIFICATE_ARN }} \
            ApiStage=${{ vars.API_STAGE_NAME }}
