name: deploy-rondeau
on:
  push:
    branches:
      - main
      - dev
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:

  deploy-auth:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup Cognito
        run: |
          aws cloudformation deploy \
          --stack-name auth-cognito \
          --template-file ./cloudformation/auth/cognito/cognito.yaml \
          --parameter-overrides \
            CallbackUrl=${{ vars.COGNITO_CALLBACK_URL }} \
            LogoutUrl=${{ vars.COGNITO_LOGOUT_URL }}

  deploy-api:
    needs: deploy-auth
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Create IAM roles
        run: |
          aws cloudformation deploy \
          --stack-name api-iam \
          --capabilities CAPABILITY_NAMED_IAM \
          --template-file ./cloudformation/api/iam/iam.yaml

      - name: Setup S3 bucket
        run: |
          aws cloudformation deploy \
          --stack-name api-s3 \
          --template-file ./cloudformation/api/s3/s3.yaml \
          --parameter-overrides \
            LambdaSourceBucketName=${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}

      - name: Build and upload Lambda zip files
        env:
          LAMBDA_SOURCE_BUCKET_NAME: ${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}
        run: |
          chmod +x ./cloudformation/api/lambda/lambdaUpload.sh
          ./cloudformation/api/lambda/lambdaUpload.sh

      - name: Create Lambdas
        run: |
          aws cloudformation deploy \
          --stack-name api-lambda \
          --template-file ./cloudformation/api/lambda/lambda.yaml \
          --parameter-overrides \
            AppBaseUrl=${{ vars.APP_BASE_URL }} \
            LambdaSourceBucketName=${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}

      - name: Upload OpenAPI specification for APIGateway
        run: |
          aws s3 cp ./cloudformation/api/apigateway/openapi.yaml s3://${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}

      - name: Create APIGateway and resources
        run: |
          SPEC_HASH=$(sha256sum ./cloudformation/api/apigateway/openapi.yaml | cut -d' ' -f1)

          aws s3 cp ./cloudformation/api/apigateway/openapi.yaml s3://${{ vars.LAMBDA_SOURCE_BUCKET_NAME }}/openapi.yaml

          aws cloudformation deploy \
          --stack-name api-apigateway \
          --template-file ./cloudformation/api/apigateway/apigateway.yaml \
          --parameter-overrides \
            LambdaSourceBucketName=${{ vars.LAMBDA_SOURCE_BUCKET_NAME }} \
            DeploymentId=$SPEC_HASH \
            Stage=${{ vars.APT_GATEWAY_STAGE }}

  deploy-frontend:
    needs: deploy-api
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}

      - name: Setup S3 bucket
        run: |
          aws cloudformation deploy \
          --stack-name api-s3 \
          --template-file ./cloudformation/frontend/s3/s3.yaml \
          --parameter-overrides \
            FrontendAssetsBucketName=${{ vars.FRONTEND_ASSETS_BUCKET_NAME }}

